name: numeral
description: >-
  A Dart library for formatting and manipulating numbers.

  Format number into beautiful string.

  ```
    Numeral(1000000000000).value(); // > 1T
  ```

version: 1.0.0
homepage: https://github.com/medz/numeral.dart
repository: https://github.com/medz/numeral.dart
issue_tracker: https://github.com/medz/numeral.dart/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: any
