name: numeral
description: >-
  A Dart library for Format number into beautiful string,
  Format the number into a beautiful, readable and short string.

version: 3.0.0
repository: https://github.com/medz/numeral.dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
