name: numeral
description: >-
  A Dart library for Format number into beautiful string,
  Format the number into a beautiful, readable and short string.

version: 3.0.0
homepage: https://github.com/medz/numeral.dart
repository: https://github.com/medz/numeral.dart
issue_tracker: https://github.com/medz/numeral.dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
